### PR TITLE
Set environments to prod

### PR DESCRIPTION
**Pull request by MKodde**
Tweak the release script:

1. Run the release in prod mode, with debug disabled
2. The dev cache folder is now no longer created in the Tarbal. A prod cache is added instead.

### CODE REVIEW

**Comment by MKodde** [comment]
This is an example tarbal that would be created from this makeRelease.sh script.
[OpenConext-user-lifecycle-maintenance_update-release-script.tar.gz](https://github.com/OpenConext/OpenConext-user-lifecycle/files/8409463/OpenConext-user-lifecycle-maintenance_update-release-script.tar.gz)

**Comment by quartje** [comment]
This included the prod cache already warmed up in the tarball. Is that the recommended way to ship this? Or should the cache be explicitly warmed up when deploying the app?

**Comment by MKodde** [comment]
Running Composer install on a symfony app also performs a cache:clear. Which in turn warms up the cache. 

Having the cache in the tarbal is extra kilobytes. And might contain data that is not portable at all.

**Comment by MKodde** [comment]
[OpenConext-user-lifecycle-maintenance_update-release-script.tar.gz](https://github.com/OpenConext/OpenConext-user-lifecycle/files/8418498/OpenConext-user-lifecycle-maintenance_update-release-script.tar.gz)

:point_up: This is the current state of affairs @quartje

**Review by quartje — APPROVED** [review]

**Pull request merged**
